sudo: required
services:
  - docker

before_install:
  - docker build -t cml8198/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cml8198/react-test npm test -- --coverage

after_success:
  - docker build -t cml8198/multi-client ./client
  - docker build -t cml8198/multi-nginx ./nginx
  - docker build -t cml8198/multi-server ./server
  - docker build -t cml8198/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cml8198/multi-client
  - docker push cml8198/multi-nginx
  - docker push cml8198/multi-server
  - docker push cml8198/multi-worker
